version: "3.9"
name: stable-diffusion-webui

services:
  stable-diffusion-webui:
    build:
      context: .
    image: "stable-diffusion-webui:latest"
    container_name: "stable-diffusion-webui"
    environment:
      TZ: Asia/Taipei
      CLI_ARGS: --no-half --precision full --allow-code --enable-insecure-extension-access --api --skip-torch-cuda-test
    # volumes:
    #   - type: bind
    #     source: ./config.json
    #     target: /app/config.json
    ports:
      - "5001:5000"
    restart: unless-stopped
